version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - local

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "query-transaction-v1"
    depends_on:
      - zookeeper
    networks:
      - local

  api:
    build: ./ApiGatewayService
    container_name: ApiGatewayService
    ports:
      - 8080:8080
    depends_on:
      - kafka
    networks:
      - local

  auth:
    build: ./AuthService
    container_name: AuthService
    ports:
      - 8081:8081
    depends_on:
      - kafka
    networks:
      - local

  transaction:
    build: ./TransactionManagementService
    container_name: TransactionManagementService
    ports:
      - 8082:8082
    depends_on:
      - kafka
    networks:
      - local

networks:

  local:
    driver: bridge
