version: "3"

services:
  user:
    build: ./ApiGatewayService .
    ports:
      - "8080:8080"
    networks:
      - local
  trip:
    build: ./AuthService .
    ports:
      - "8081:8081"
    networks:
      - local
  pricing:
    build: ./TransactionManagementService .
    ports:
      - "8082:8082"
    networks:
      - local
  match:
    build: ./ExchangeRateService .
    ports:
      - "8083:8083"
    networks:
      - local
networks:

  local:
    driver: bridge