version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - local

  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    hostname: kafka1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_KRAFT_CLUSTER_ID=transaction-cluster
      - KAFKA_KRAFT_NUM_REPLICAS=2
      - KAFKA_KRAFT_NUM_PARTITIONS=3
    depends_on:
      - zookeeper
    networks:
      - local
    volumes:
      - ./kafka1/data:/bitnami/kafka/data
      - ./kafka1/logs:/bitnami/kafka/logs

#  kafka2:
#    image: confluentinc/cp-kafka:latest
#    hostname: kafka2
#    container_name: kafka2
#    ports:
#      - '9093:9093'
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
#      - KAFKA_LISTENERS=PLAINTEXT://:9093
#      - KAFKA_BROKER_ID=2
#      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
#      - KAFKA_KRAFT_CLUSTER_ID=transaction-cluster
#      - KAFKA_KRAFT_NUM_REPLICAS=2
#      - KAFKA_KRAFT_NUM_PARTITIONS=3
#      - KAFKA_DEFAULT_TOPIC=query_transaction_v1
#      - KAFKA_DEFAULT_GROUP_ID=transaction_group
#    depends_on:
#      - zookeeper
#    networks:
#      - local
#    volumes:
#      - ./kafka2/data:/bitnami/kafka/data
#      - ./kafka2/logs:/bitnami/kafka/logs
networks:
  local:
    driver: bridge
#
#  api:
#    build: ./ApiGatewayService
#    container_name: ApiGatewayService
#    ports:
#      - 8080:8080
#    depends_on:
#      - kafka
#    networks:
#      - local
#
#  auth:
#    build: ./AuthService
#    container_name: AuthService
#    ports:
#      - 9000:9000
#    depends_on:
#      - kafka
#    networks:
#      - local
#
#  transaction:
#    build: ./TransactionManagementService
#    container_name: TransactionManagementService
#    ports:
#      - 8082:8082
#    depends_on:
#      - kafka
#    networks:
#      - local


